
name: Buildapp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1.6.0
      - name: בניית אפלקצית אנגולר
        run: npm run build
      - name: S3 Sync
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read dist/Host-Application/ s3://appbuilder.staging.cloudonix.io/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"

